REPO_URLS=\
https://github.com/f5/unovis \
https://github.com/f5/otel-arrow-adapter \
https://github.com/f5/.github \
https://github.com/F5Networks/k8s-bigip-ctlr \
https://github.com/F5Networks/terraform-provider-bigip \
https://github.com/F5Networks/f5-openstack-agent \
https://github.com/F5Networks/f5-telemetry-streaming \
https://github.com/F5Networks/SecondSight \
https://github.com/F5Networks/f5-ansible-f5modules \
https://github.com/F5Networks/f5-ansible-bigip \
https://github.com/F5Networks/f5-ansible \
https://github.com/F5Networks/f5-cloud-libs \
https://github.com/F5Networks/terraform-azure-bigip-module \
https://github.com/F5Networks/terraform-gcp-bigip-module \
https://github.com/F5Networks/terraform-aws-bigip-module \
https://github.com/F5Networks/f5-ansible-f5os \
https://github.com/F5Networks/f5-appsvcs-templates \
https://github.com/F5Networks/f5-common-python \
https://github.com/F5Networks/f5-declarative-onboarding \
https://github.com/F5Networks/f5-openstack-lbaasv2-driver \
https://github.com/F5Networks/f5-cloud-libs-gce \
https://github.com/F5Networks/f5-cloud-libs-aws \
https://github.com/F5Networks/f5-cloud-libs-azure \
https://github.com/F5Networks/f5-ipam-controller \
https://github.com/F5Networks/charts \
https://github.com/F5Networks/f5-google-gdm-templates \
https://github.com/F5Networks/f5-azure-arm-templates \
https://github.com/F5Networks/f5-aws-cloudformation \
https://github.com/F5Networks/f5-azure-arm-templates-v2 \
https://github.com/F5Networks/f5-google-gdm-templates-v2 \
https://github.com/F5Networks/f5-aws-cloudformation-v2 \
https://github.com/F5Networks/f5-icontrol-rest-python \
https://github.com/F5Networks/f5-bigip-runtime-init \
https://github.com/F5Networks/f5-cloud-failover-extension \
https://github.com/F5Networks/f5-appsvcs-extension \
https://github.com/F5Networks/f5-aci-servicecenter \
https://github.com/F5Networks/f5-nfv-solutions \
https://github.com/F5Networks/f5-openstack-docs \
https://github.com/F5Networks/quickstart-f5-big-ip-virtual-edition-ha \
https://github.com/F5Networks/f5-ci-docs \
https://github.com/F5Networks/quic-lb \
https://github.com/F5Networks/f5-lbaas-dashboard \
https://github.com/F5Networks/f5-adcaas-openstack \
https://github.com/F5Networks/dynamic-taps \
https://github.com/F5Networks/f5-cloud-libs-openstack \
https://github.com/F5Networks/networking-f5 \
https://github.com/F5Networks/f5-openstack-image-prep \
https://github.com/F5Networks/f5-openstack-heat-plugins \
https://github.com/F5Networks/f5-openstack-heat \
https://github.com/F5Networks/f5-openstack-hot \
https://github.com/F5Networks/docker-images \
https://github.com/F5Networks/f5cs-sdk \
https://github.com/F5Networks/external-dns \
https://github.com/F5Networks/f5-cloud-iapps \
https://github.com/F5Networks/pytest-symbols \
https://github.com/F5Networks/f5-neutron-lbaas \
https://github.com/F5Networks/terraform-provider-bigip-version0.12 \
https://github.com/F5Networks/f5-cloud-libs-consul \
https://github.com/F5Networks/marathon-bigip-ctlr \
https://github.com/F5Networks/cf-bigip-ctlr \
https://github.com/F5Networks/f5-beacon \
https://github.com/F5Networks/f5-azure-stack-arm-templates \
https://github.com/F5Networks/f5-ipam-ctlr \
https://github.com/F5Networks/neutron-lbaas-dashboard \
https://github.com/F5Networks/f5-vmware-vcenter-templates \
https://github.com/F5Networks/f5-neutron-lbaas-dashboard-docs \
https://github.com/F5Networks/bigsuds \
https://github.com/F5Networks/neutron-lbaas \
https://github.com/F5Networks/f5networks.github.io \
https://github.com/F5Networks/f5-cloud-workers \
https://github.com/F5Networks/f5-automation-labs \
https://github.com/F5Networks/f5-openstack-test \
https://github.com/F5Networks/f5-openstack-lbaasv1 \
https://github.com/F5Networks/pytest_f5sdk \
https://github.com/F5Networks/linerate_api_docs \
https://github.com/F5Networks/neutron-specs \
https://github.com/f5devcentral/nap-policy-management \
https://github.com/f5devcentral/spa-demo-app \
https://github.com/f5devcentral/f5-agility-labs-nginx \
https://github.com/f5devcentral/modern_app_jumpstart_workshop \
https://github.com/f5devcentral/f5-professional-services \
https://github.com/f5devcentral/f5-bd-ansible-labs \
https://github.com/f5devcentral/f5-agility-labs-threat-stack \
https://github.com/f5devcentral/f5-ci-docs \
https://github.com/f5devcentral/bigip-kubernetes-gateway \
https://github.com/f5devcentral/cilium \
https://github.com/f5devcentral/f5-rseries-training \
https://github.com/f5devcentral/aip-demo-udf \
https://github.com/f5devcentral/f5-fast-core \
https://github.com/f5devcentral/vscode-f5 \
https://github.com/f5devcentral/f5xc-internal-http-lb \
https://github.com/f5devcentral/vscode-f5-flipper \
https://github.com/f5devcentral/f5-bd-ansible-usecases-docs \
https://github.com/f5devcentral/f5-hybrid-security-architectures \
https://github.com/f5devcentral/modern_app_jumpstart_workshop_infra \
https://github.com/f5devcentral/azure-waf-solution-template \
https://github.com/f5devcentral/f5-cis-docs \
https://github.com/f5devcentral/adaptiveapps \
https://github.com/f5devcentral/f5-sphinx-theme \
https://github.com/f5devcentral/openapi-url-watcher \
https://github.com/f5devcentral/terraform-google-f5-automation-factory \
https://github.com/f5devcentral/msda-nacos \
https://github.com/f5devcentral/msda-consul \
https://github.com/f5devcentral/analytics-vendor-dashboards \
https://github.com/f5devcentral/f5-agility-labs-xc \
https://github.com/f5devcentral/msda-zookeeper \
https://github.com/f5devcentral/f5xc-solutions \
https://github.com/f5devcentral/xchacedemoguide \
https://github.com/f5devcentral/msda-kubernetes \
https://github.com/f5devcentral/f5-agility-labs-iam \
https://github.com/f5devcentral/msda-eureka \
https://github.com/f5devcentral/f5-azure-saca \
https://github.com/f5devcentral/f5-sdk-js \
https://github.com/f5devcentral/f5-beacon \
https://github.com/f5devcentral/certified-operators \
https://github.com/f5devcentral/asmevents \
https://github.com/f5devcentral/go-bigip \
https://github.com/f5devcentral/f5xc-aws-ce-multinic \
https://github.com/f5devcentral/container-egress-service \
https://github.com/f5devcentral/F5-SE-Outcome-Based-Learning \
https://github.com/f5devcentral/f5-agility-labs-cert \
https://github.com/f5devcentral/f5-journeys \
https://github.com/f5devcentral/f5-atg-shared-utilities \
https://github.com/f5devcentral/f5-velos-training \
https://github.com/f5devcentral/sentence-demo-app \
https://github.com/f5devcentral/fdc_org_mgmt \
https://github.com/f5devcentral/fig-config-drive-builder \
https://github.com/f5devcentral/fig-flask-basic \
https://github.com/f5devcentral/f5-agility-labs-template-ARM64-x86_64-RM \
https://github.com/f5devcentral/f5-agility-labs-waf \
https://github.com/f5devcentral/access-solutions \
https://github.com/f5devcentral/f5xc-mcn-learning-week \
https://github.com/f5devcentral/ibmcloud_schematics_bigip_multinic_declared \
https://github.com/f5devcentral/f5-cccl \
https://github.com/f5devcentral/xcwaapdemoguide \
https://github.com/f5devcentral/f5-demo-httpd \
https://github.com/f5devcentral/tmos-cloudinit \
https://github.com/f5devcentral/xcmcndemoguide \
https://github.com/f5devcentral/terraform-aws-ec2-nginx-plus \
https://github.com/f5devcentral/f5-icontrol-trusted-devices \
https://github.com/f5devcentral/volterra-management \
https://github.com/f5devcentral/homebrew-vesctl \
https://github.com/f5devcentral/f5-terraform-consul-sd-webinar \
https://github.com/f5devcentral/f5xc-shop-demo \
https://github.com/f5devcentral/msra-nacos \
https://github.com/f5devcentral/msra-eureka \
https://github.com/f5devcentral/msra-consul \
https://github.com/f5devcentral/f5-ctlr-agent \
https://github.com/f5devcentral/atg-storage \
https://github.com/f5devcentral/f5xc-resource-query \
https://github.com/f5devcentral/client-side-defense \
https://github.com/f5devcentral/fast-terraform \
https://github.com/f5devcentral/Log4j-mitigation-using-F5-XC \
https://github.com/f5devcentral/f5-bd-mcd \
https://github.com/f5devcentral/owasp-injection-mitigation \
https://github.com/f5devcentral/f5-conx-core \
https://github.com/f5devcentral/access-infra \
https://github.com/f5devcentral/fig-express-basic \
https://github.com/f5devcentral/malicious-user-detection-mitigation \
https://github.com/f5devcentral/terraform-bigip-postbuild-config \
https://github.com/f5devcentral/nginx-waf-templates \
https://github.com/f5devcentral/f5-declaration-validator \
https://github.com/f5devcentral/f5-telemetry-probing-metrics \
https://github.com/f5devcentral/terraform-volterra \
https://github.com/f5devcentral/f5-waf-policy-editor \
https://github.com/f5devcentral/vscode-f5-xc \
https://github.com/f5devcentral/f5-digital-customer-engagement-center \
https://github.com/f5devcentral/modern_app_jumpstart_workshop-1 \
https://github.com/f5devcentral/f5-bd-ansible-usecases \
https://github.com/f5devcentral/msda-etcd \
https://github.com/f5devcentral/MSDA-Demo \
https://github.com/f5devcentral/f5-agility-labs \
https://github.com/f5devcentral/xcwaapcdnguide \
https://github.com/f5devcentral/sslo-script-tools \
https://github.com/f5devcentral/appstack-aws-site \
https://github.com/f5devcentral/vscode-f5-chariot \
https://github.com/f5devcentral/volterra-api-sec \
https://github.com/f5devcentral/f5-telemetry-analytics \
https://github.com/f5devcentral/ForcesFor \
https://github.com/f5devcentral/f5-automation-config-converter \
https://github.com/f5devcentral/ansible-role-nginx \
https://github.com/f5devcentral/vscode-f5-apm \
https://github.com/f5devcentral/f5-agility-labs-automation \
https://github.com/f5devcentral/nap-dos-elk-dashboards \
https://github.com/f5devcentral/f5-big-iq-lab \
https://github.com/f5devcentral/access-labs \
https://github.com/f5devcentral/f5-bd-sre-demo \
https://github.com/f5devcentral/f5-journeys-lab-ucs-modifier \
https://github.com/f5devcentral/f5-bigip-image-generator \
https://github.com/f5devcentral/lets-encrypt-python \
https://github.com/f5devcentral/awaf-terraform \
https://github.com/f5devcentral/awaf-tf \
https://github.com/f5devcentral/f5-bd-ansible-workshops \
https://github.com/f5devcentral/volterra-workshop-10x \
https://github.com/f5devcentral/xc-logProxy \
https://github.com/f5devcentral/f5xc-solution-packages \
https://github.com/f5devcentral/sslo-cloud-templates \
https://github.com/f5devcentral/f5-cli \
https://github.com/f5devcentral/terraform-bigip-consul-sync-event \
https://github.com/f5devcentral/NIC-SM-Sandbox---Fresh-Config \
https://github.com/f5devcentral/big-ip-atc-ready \
https://github.com/f5devcentral/f5-corkscrew \
https://github.com/f5devcentral/sslo-o365-update \
https://github.com/f5devcentral/f5-agility-labs-template \
https://github.com/f5devcentral/partner-charts \
https://github.com/f5devcentral/f5-agility-labs-adc \
https://github.com/f5devcentral/f5-automation-labs \
https://github.com/f5devcentral/f5-agility-labs-service-discovery \
https://github.com/f5devcentral/f5-agility-labs-analytics \
https://github.com/f5devcentral/f5-agility-labs-sslviz \
https://github.com/f5devcentral/f5-agility-labs-irules \
https://github.com/f5devcentral/f5-agility-labs-vdi \
https://github.com/f5devcentral/f5-agility-labs-private-cloud \
https://github.com/f5devcentral/f5-agility-labs-icontrol-lx \
https://github.com/f5devcentral/f5-agility-labs-fps \
https://github.com/f5devcentral/f5-agility-labs-firewall \
https://github.com/f5devcentral/f5-agility-labs-ddos \
https://github.com/f5devcentral/f5-agility-labs-dns \
https://github.com/f5devcentral/f5-agility-labs-public-cloud \
https://github.com/f5devcentral/f5-agility_GC_Terraform_ATC \
https://github.com/f5devcentral/f5-agility-labs-big-iq \
https://github.com/f5devcentral/f5-agility-labs-containers \
https://github.com/f5devcentral/f5-bd-ansible-security-lab-docs \
https://github.com/f5devcentral/f5-certificate-rotate \
https://github.com/f5devcentral/f5go \
https://github.com/f5devcentral/ansible-role-bigiq_as3_device_disaster_recovery \
https://github.com/f5devcentral/f5-big-iq-pm-team \
https://github.com/f5devcentral/ml_sqli_detector \
https://github.com/f5devcentral/volt-demo-app \
https://github.com/f5devcentral/DevSecOps-Workshop \
https://github.com/f5devcentral/f5-big-iq-trial-quick-start \
https://github.com/f5devcentral/f5xc-auto-waap-min \
https://github.com/f5devcentral/f5-oci-failover \
https://github.com/f5devcentral/waf-templates \
https://github.com/f5devcentral/f5-asm-policy-templates \
https://github.com/f5devcentral/waf-baseline-policy \
https://github.com/f5devcentral/f5-waap \
https://github.com/f5devcentral/f5-distributed-cloud-labs-101 \
https://github.com/f5devcentral/f5-sdk-python \
https://github.com/f5devcentral/ansible-role-bigiq_move_app_dashboard \
https://github.com/f5devcentral/ansible-role-bigiq_migrate_apps \
https://github.com/f5devcentral/as3-bluegreen \
https://github.com/f5devcentral/ansible-role-bigiq_pinning_deploy_objects \
https://github.com/f5devcentral/irules-toolbox \
https://github.com/f5devcentral/nginx_microservices_march_labs \
https://github.com/f5devcentral/nginx-plus-dos-dashboard \
https://github.com/f5devcentral/terraform-google-f5-bigip-ha \
https://github.com/f5devcentral/ansible-role-f5_atc_deploy_declaration \
https://github.com/f5devcentral/terraform-aws-bigip \
https://github.com/f5devcentral/volterra-azure-sca \
https://github.com/f5devcentral/shapeRank \
https://github.com/f5devcentral/f5-entoli \
https://github.com/f5devcentral/f5-agent-auditor \
https://github.com/f5devcentral/aws-waf-solution-template \
https://github.com/f5devcentral/f5-waf-elk-dashboards \
https://github.com/f5devcentral/f5-bd-gslb-tool \
https://github.com/f5devcentral/f5-cilium \
https://github.com/f5devcentral/f5-bados-app \
https://github.com/f5devcentral/ibmcloud_schematics_bigiq_multinic \
https://github.com/f5devcentral/terraform-gcp-bigip-module \
https://github.com/f5devcentral/vscode-nim \
https://github.com/f5devcentral/volterra-eks-vk8s-guide \
https://github.com/f5devcentral/terraform-aws-bigip-module \
https://github.com/f5devcentral/terraform-azure-bigip-module \
https://github.com/f5devcentral/f5-icontrol-gateway \
https://github.com/f5devcentral/f5-bados-grafana-docker \
https://github.com/f5devcentral/terraform-aci-bigip \
https://github.com/f5devcentral/adc-telemetry-based-autoscaling \
https://github.com/f5devcentral/ibmcloud_schematics_bigip_multinic_public_images \
https://github.com/f5devcentral/f5-bd-bigip-vmware-day0-aap \
https://github.com/f5devcentral/terraform-gcp-f5-sca \
https://github.com/f5devcentral/volterra-gke-vk8s-guide \
https://github.com/f5devcentral/volterra-aks-vk8s-guide \
https://github.com/f5devcentral/f5-bd-bigip-vmware-day0 \
https://github.com/f5devcentral/bigip-telmetry-based-autoscaling \
https://github.com/f5devcentral/f5-bd-ansible-lessons \
https://github.com/f5devcentral/gslb_dns_monitor \
https://github.com/f5devcentral/terraform-udf \
https://github.com/f5devcentral/nginx-plus-api-gateway-lab \
https://github.com/f5devcentral/f5-bigip-shared-vpc-discovery \
https://github.com/f5devcentral/f5-fast-servicenow-demo \
https://github.com/f5devcentral/ansible-role-bigiq_onboard \
https://github.com/f5devcentral/f5-puppet \
https://github.com/f5devcentral/nginx-njs-usecases \
https://github.com/f5devcentral/f5-vnfmanager-labs \
https://github.com/f5devcentral/f5-bigip-agc-config-guides \
https://github.com/f5devcentral/terraform-provider-aci \
https://github.com/f5devcentral/mockhttpclient \
https://github.com/f5devcentral/volterra-onboarding \
https://github.com/f5devcentral/f5-k8s-demo \
https://github.com/f5devcentral/f5-beacon-lab \
https://github.com/f5devcentral/f5-aws-ecs-anywhere-sample \
https://github.com/f5devcentral/project-jarvis \
https://github.com/f5devcentral/f5-bd-tanzu-tkg-bigip \
https://github.com/f5devcentral/f5-bigip-sync-tool \
https://github.com/f5devcentral/terraform-bigip-do-builder \
https://github.com/f5devcentral/f5-bd-tanzu-tkg-nginxplus \
https://github.com/f5devcentral/terraform-bigip-app-consul-sync-nia \
https://github.com/f5devcentral/f5-tgw-examples \
https://github.com/f5devcentral/f5-bd-ansible-provisioner-docs \
https://github.com/f5devcentral/f5-demo-consul \
https://github.com/f5devcentral/f5-ansible-bigip \
https://github.com/f5devcentral/f5-big-iq \
https://github.com/f5devcentral/f5-gsts-labs-ansible-cookbook \
https://github.com/f5devcentral/f5-aws-lambda-proxy \
https://github.com/f5devcentral/f5-ansible-cloudservices \
https://github.com/f5devcentral/f5-bd-horizon-iapp-deploy \
https://github.com/f5devcentral/adpm-agility \
https://github.com/f5devcentral/UDF-DevOps-Base \
https://github.com/f5devcentral/ansible-tower-workshop-examples \
https://github.com/f5devcentral/f5-ipam-controller \
https://github.com/f5devcentral/bigip-ci \
https://github.com/f5devcentral/f5-ilx-example \
https://github.com/f5devcentral/terraform-cloud-azure-bigip-demo \
https://github.com/f5devcentral/f5-cloudservice-eap-lb-lab \
https://github.com/f5devcentral/f5-cloudservicelab \
https://github.com/f5devcentral/f5-cloudservicednslab \
https://github.com/f5devcentral/f5-cloudserviceeaplab \
https://github.com/f5devcentral/f5-tls-automation \
https://github.com/f5devcentral/f2a \
https://github.com/f5devcentral/ansible-bigip-letsencrypt-http01 \
https://github.com/f5devcentral/f5-demo-app \
https://github.com/f5devcentral/f5_ci_with_action \
https://github.com/f5devcentral/fluent-plugin-f5-beacon \
https://github.com/f5devcentral/ansible-role-register_dcd \
https://github.com/f5devcentral/ansible-role-bigiq_create_ve \
https://github.com/f5devcentral/ibmcloud_schematics_bigip_multinic \
https://github.com/f5devcentral/f5-cloudservice-eap-cloudfront \
https://github.com/f5devcentral/f5-bd-FASTexample \
https://github.com/f5devcentral/grpc-js-0.2-modified \
https://github.com/f5devcentral/FAS-provisoner-terraform \
https://github.com/f5devcentral/f5-icontrol-library-dotnet \
https://github.com/f5devcentral/automate-one-thing \
https://github.com/f5devcentral/ansible-role-bigiq_apps_rbac \
https://github.com/f5devcentral/project-chariot \
https://github.com/f5devcentral/udf-ansible-inventory-plugin \
https://github.com/f5devcentral/terraform-azure-bigiq \
https://github.com/f5devcentral/bigip_terminating_gateway \
https://github.com/f5devcentral/f5-big-iq-onboarding \
https://github.com/f5devcentral/f5-bd-consul-sd-webinar \
https://github.com/f5devcentral/f5-bigip-runtime-init \
https://github.com/f5devcentral/f5-bd-tgwdoc \
https://github.com/f5devcentral/bigip-tgw \
https://github.com/f5devcentral/Azure-AD_F5-Advanced-Guided-Configuration-Ver-7.-0-Integration \
https://github.com/f5devcentral/f5-automated-backup-iapp \
https://github.com/f5devcentral/cve-2020-5902-ioc-bigip-checker \
https://github.com/f5devcentral/f5-office365-ip-url-automation \
https://github.com/f5devcentral/ibmcloud \
https://github.com/f5devcentral/terraform-aws-f5-sca \
https://github.com/f5devcentral/f5-intro-to-docker \
https://github.com/f5devcentral/campfire \
https://github.com/f5devcentral/Ansible-Terraform-Cloud-Templates \
https://github.com/f5devcentral/f5-big-ip-cloud-edition-trial-quick-start \
https://github.com/f5devcentral/terraform-provider-bigip \
https://github.com/f5devcentral/f5-as3-usecases \
https://github.com/f5devcentral/f5-tetration \
https://github.com/f5devcentral/f5-appsvcs-templates \
https://github.com/f5devcentral/f5-cloud-failover-extension \
https://github.com/f5devcentral/cloudserviceeaplab \
https://github.com/f5devcentral/f5-azure-mag-arm-templates \
https://github.com/f5devcentral/terraform-provider-bigip-old \
https://github.com/f5devcentral/f5-terraform \
https://github.com/f5devcentral/F5AppSvcDemo \
https://github.com/f5devcentral/FAS-provisioner \
https://github.com/f5devcentral/f5-icontrol-codeshare-python \
https://github.com/f5devcentral/f5-agility-lab-terraform101 \
https://github.com/f5devcentral/ansible-role-f5app_services_package \
https://github.com/f5devcentral/f5_nexus_9k_playbook \
https://github.com/f5devcentral/FAS-ansible-workshop-101 \
https://github.com/f5devcentral/f5-nodejs \
https://github.com/f5devcentral/bigip-ansible-deploy-iapp \
https://github.com/f5devcentral/f5-tmsh2iapp \
https://github.com/f5devcentral/project_chainlinks \
https://github.com/f5devcentral/ansible-role-f5ansible \
https://github.com/f5devcentral/f5-security-hub-extension \
https://github.com/f5devcentral/f5-ansible-asm-example \
https://github.com/f5devcentral/tmos-configdrive-builder \
https://github.com/f5devcentral/f5-ansible-sandbox \
https://github.com/f5devcentral/f5-aci-labs \
https://github.com/f5devcentral/f5-offline-dc-docsets \
https://github.com/f5devcentral/f5-rest-examples \
https://github.com/f5devcentral/ansible-role-bigip_hardening \
https://github.com/f5devcentral/ansible-role-dns_express \
https://github.com/f5devcentral/ansible-role-bigip_to_ansible \
https://github.com/f5devcentral/ansible-role-bigip_onboard \
https://github.com/f5devcentral/ansible-role-bigip_ha_cluster \
https://github.com/f5devcentral/ansible-role-bigip_gslb \
https://github.com/f5devcentral/ansible-role-backup_config \
https://github.com/f5devcentral/f5-icontrollx-dev-kit \
https://github.com/f5devcentral/BigStats \
https://github.com/f5devcentral/quickstart-f5-big-ip-virtual-edition \
https://github.com/f5devcentral/f5-asm-lx \
https://github.com/f5devcentral/ansible-role-asm_policy \
https://github.com/f5devcentral/ansible-role-bigip_device_auth \
https://github.com/f5devcentral/ansible-role-bigip_dns_cache \
https://github.com/f5devcentral/f5-waf-audit \
https://github.com/f5devcentral/f5-azure-ha \
https://github.com/f5devcentral/f5-bd-routing-vip \
https://github.com/f5devcentral/f5-cloud-libs \
https://github.com/f5devcentral/f5-aci-integration-automation-ansible \
https://github.com/f5devcentral/f5-terraform-agility2018 \
https://github.com/f5devcentral/f5devcentral.github.io \
https://github.com/f5devcentral/f5-bd-vcpe-demo \
https://github.com/f5devcentral/as3-alexa \
https://github.com/f5devcentral/f5-101-lab-kubernetes \
https://github.com/f5devcentral/f5-icontrol-library-java \
https://github.com/f5devcentral/pytest-symbols \
https://github.com/f5devcentral/pytest-autolog \
https://github.com/f5devcentral/pytest-meta \
https://github.com/f5devcentral/f5-cloud-functions \
https://github.com/f5devcentral/f5-as3-examples \
https://github.com/f5devcentral/f5-packer-templates \
https://github.com/f5devcentral/f5-super-netops-container \
https://github.com/f5devcentral/f5-csv2cccl \
https://github.com/f5devcentral/f5-cloud-init-examples \
https://github.com/f5devcentral/f5-rest \
https://github.com/f5devcentral/bigip-ansible-virtualserver \
https://github.com/f5devcentral/f5-hello-world \
https://github.com/f5devcentral/f5-eclipse-plugin \
https://github.com/f5devcentral/f5-vagrant-files \
https://github.com/f5devcentral/f5-icontrol-powershell-snapin \
https://github.com/f5devcentral/i2ac \
https://github.com/f5devcentral/f5-openstack-ansible \
https://github.com/f5devcentral/cf-bigip-buildpack \
https://github.com/f5devcentral/f5-azure-multi-nic \
https://github.com/f5devcentral/f5_openstack_validation_tools \
https://github.com/f5devcentral/f5-demo-php \
https://github.com/f5devcentral/f5-aws-autoscale \
https://github.com/f5devcentral/f5-cloud-month \
https://github.com/f5devcentral/f5-dns-automation-demo-12-1-x \
https://github.com/f5devcentral/f5-ihealth-api-examples \
https://github.com/f5devcentral/f5-azure-waf-community \
https://github.com/f5devcentral/aws-deployments \
https://github.com/f5devcentral/SdnScale \
https://github.com/f5devcentral/iControl-GettingStarted \
https://github.com/f5devcentral/f5-aws-migrate \
https://github.com/f5devcentral/f5-irule-editor \
https://github.com/f5devcentral/f5-openstack-puppet \
https://github.com/f5devcentral/f5-xforwarded-for \
https://github.com/apcj-f5/f5-pulse-snapshots \
https://github.com/apcj-f5/nap-dos-demo \
https://github.com/apcj-f5/GH-TEMPLATE-for-new-repositories \
https://github.com/apcj-f5/.github \
https://github.com/apcj-f5/arcadia-app \
https://github.com/apcj-f5/.allstar \
https://github.com/apcj-f5/.jit.io-minimum-viable-security-workflows \
https://github.com/apcj-f5/opensase \
https://github.com/apcj-f5/arcadia-app2 \
https://github.com/apcj-f5/arcadia-kubernetes \
https://github.com/apcj-f5/secure-cloud-architecture-with-volterra \
https://github.com/apcj-f5/nginx-demo-collection \
https://github.com/apcj-f5/nginx-unit-demo \
https://github.com/apcj-f5/bank-of-f5labs.dev \
https://github.com/apcj-f5/f5-azure-secure-cloud-architecture-deployment \
https://github.com/apcj-f5/nginx-sidecar-api-gateway-deployment \
https://github.com/apcj-f5/arcadia-backend \
https://github.com/apcj-f5/arcadia-frontend \
https://github.com/apcj-f5/hapi-fhir \
https://github.com/apcj-f5/f5-waf-policy-check \
https://github.com/apcj-f5/arcadia-app3 \
https://github.com/apcj-f5/f5-demo-app \
https://github.com/apcj-f5/cnf-certification \
https://github.com/apcj-f5/api-gateway-appsec \
https://github.com/apcj-f5/apcj-f5 \
https://github.com/apcj-f5/access-solutions \
https://github.com/apcj-f5/arcadia-nginx \
https://github.com/apcj-f5/ausfed-sig \
https://github.com/apcj-f5/aspen-mesh-multi-cluster-deployment \
https://github.com/apcj-f5/cloud-ingress-appsec \
https://github.com/apcj-f5/ausfed-solutions \
https://github.com/apcj-f5/f5-csd \
https://github.com/apcj-f5/container-ingress-appsec \
https://github.com/apcj-f5/data61-cdr-openbanking-poc \
https://github.com/apcj-f5/free5gc \
https://github.com/apcj-f5/nginx-waf-templates \
https://github.com/apcj-f5/nginx-waf-playbook \
https://github.com/apcj-f5/nginx-ultimate-bad-bot-blocker \
https://github.com/apcj-f5/nginx-sidecar-waf-demo \
https://github.com/apcj-f5/REST-and-GraphQL-example \
https://github.com/apcj-f5/vscode-nginx-conf \
https://github.com/apcj-f5/swapi \
https://github.com/apcj-f5/upgrade-f5-using-ansible \
https://github.com/apcj-f5/nurv \
https://github.com/apcj-f5/apcj.f5labs.dev 

rank:
	node tools/git-pulse-rank.js

clones:
	mkdir build || true; \
	cd build; \
	for url in $(REPO_URLS); do \
		git clone $$url || true; \
	done

snapshots:
	cd build; \
	for dir in */; do \
		cd $$dir && git pull && time bash ../../tools/git-pulse; \
		cp *$$(date +"%Y-%m-%d")-pulse.* ../..; \
		cd ..; \
	done;

